 version: "3.3"

 services:
   api-students:
     build: ./api-students
     ports:
       - 8000:8000
   websimple:
     build: ./websimple
     ports:
       - 8080:80
    websbonita:
     build: ./webbonita 
     ports:
       - 8081:80 #no se puede tener el mismo puerto que otro contenedor, por ello es 8081
